#!/usr/bin/env bash

# 严格模式设置
set -euo pipefail

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 检查是否为 root 用户
if [ "$(id -u)" != "0" ]; then
    echo -e "${RED}错误: 必须使用 root 用户运行此脚本！${NC}"
    exit 1
fi

# 检测系统类型
detect_system_type() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        OS_VERSION=$VERSION_ID
    else
        OS="unknown"
    fi
}

# 检测网络管理器
detect_network_manager() {
    MANAGERS=()
    systemctl is-active --quiet NetworkManager 2>/dev/null && MANAGERS+=("NetworkManager")
    systemctl is-active --quiet systemd-networkd 2>/dev/null && MANAGERS+=("systemd-networkd")
    systemctl is-active --quiet systemd-resolved 2>/dev/null && MANAGERS+=("systemd-resolved")
    pgrep -x dhcpcd >/dev/null 2>&1 && MANAGERS+=("dhcpcd")
    pgrep -x dhclient >/dev/null 2>&1 && MANAGERS+=("dhclient")
    pgrep -x udhcpc >/dev/null 2>&1 && MANAGERS+=("udhcpc")
    pgrep -x connman >/dev/null 2>&1 && MANAGERS+=("connman")
}

# DNS 服务器配置
IPV4_DNS=(
    "8.8.8.8"      # Google DNS
    "1.1.1.1"      # Cloudflare DNS
)
IPV6_DNS=(
    "2001:4860:4860::8888"  # Google IPv6 DNS
    "2001:4860:4860::8844"  # Google IPv6 DNS
)

echo -e "${GREEN}正在增强 DNS 设置并锁定防止 DHCP 和其他服务修改...${NC}"

# 检测系统类型和网络管理器
detect_system_type
detect_network_manager

echo -e "${YELLOW}检测到系统: $OS${NC}"
echo -e "${YELLOW}检测到网络管理器: ${MANAGERS[*]:-无}${NC}"

# 1. 创建 DNS 配置函数
create_resolv_conf() {
    local resolv_file="$1"
    cat > "$resolv_file" << EOF
# DNS Configuration - Locked by dns-lock script
# DO NOT EDIT - This file is automatically generated
$(for dns in "${IPV4_DNS[@]}"; do echo "nameserver $dns"; done)
$(for dns in "${IPV6_DNS[@]}"; do echo "nameserver $dns"; done)
EOF
    # 设置只读属性防止意外修改
    chattr +i "$resolv_file" 2>/dev/null || true
}

# 2. 处理 systemd-resolved
setup_systemd_resolved() {
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        echo -e "${GREEN}配置 systemd-resolved...${NC}"
        
        # 配置 resolved.conf
        cat > /etc/systemd/resolved.conf << EOF
[Resolve]
DNS=${IPV4_DNS[0]} ${IPV4_DNS[1]} ${IPV6_DNS[0]} ${IPV6_DNS[1]}
FallbackDNS=8.8.4.4 1.0.0.1
LLMNR=no
MulticastDNS=no
DNSSEC=no
DNSOverTLS=no
Cache=no
DNSStubListener=no
ReadEtcHosts=yes
EOF
        
        # 确保 /etc/resolv.conf 是符号链接
        if [ -L /etc/resolv.conf ]; then
            rm -f /etc/resolv.conf
        else
            rm -f /etc/resolv.conf
        fi
        ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
        
        systemctl restart systemd-resolved
        return 0
    fi
    return 1
}

# 3. 处理 NetworkManager
setup_networkmanager() {
    if systemctl is-active --quiet NetworkManager 2>/dev/null; then
        echo -e "${GREEN}配置 NetworkManager...${NC}"
        
        # 创建 DNS 锁定配置
        cat > /etc/NetworkManager/conf.d/90-dns-lock.conf << EOF
[main]
dns=none
rc-manager=unmanaged
EOF

        # 创建连接级别的 DNS 配置
        cat > /etc/NetworkManager/conf.d/91-dns-servers.conf << EOF
[global-dns-domain-*]
servers=${IPV4_DNS[0]},${IPV4_DNS[1]},${IPV6_DNS[0]},${IPV6_DNS[1]}
EOF

        # 重启 NetworkManager
        systemctl restart NetworkManager
        return 0
    fi
    return 1
}

# 4. 处理 dhcpcd
setup_dhcpcd() {
    if [ -f /etc/dhcpcd.conf ]; then
        echo -e "${GREEN}配置 dhcpcd...${NC}"
        
        # 备份原配置
        cp -f /etc/dhcpcd.conf /etc/dhcpcd.conf.backup
        
        # 删除已有相关配置
        sed -i '/^nohook resolv.conf/d' /etc/dhcpcd.conf
        sed -i '/^static domain_name_servers/d' /etc/dhcpcd.conf
        
        # 添加禁止钩子和静态 DNS
        echo "" >> /etc/dhcpcd.conf
        echo "# DNS Lock Configuration" >> /etc/dhcpcd.conf
        echo "nohook resolv.conf" >> /etc/dhcpcd.conf
        echo "static domain_name_servers=${IPV4_DNS[0]} ${IPV4_DNS[1]} ${IPV6_DNS[0]} ${IPV6_DNS[1]}" >> /etc/dhcpcd.conf
        
        # 重启 dhcpcd 如果正在运行
        if pgrep -x dhcpcd >/dev/null 2>&1; then
            systemctl restart dhcpcd 2>/dev/null || rc-service dhcpcd restart 2>/dev/null || true
        fi
        return 0
    fi
    return 1
}

# 5. 处理 udhcpc
setup_udhcpc() {
    if [ -d /etc/udhcpc ] || command -v udhcpc >/dev/null 2>&1; then
        echo -e "${GREEN}配置 udhcpc...${NC}"
        mkdir -p /etc/udhcpc/
        echo "RESOLV_CONF=no" > /etc/udhcpc/udhcpc.conf
        return 0
    fi
    return 1
}

# 6. 处理传统的 resolv.conf (适用于不使用网络管理器的系统)
setup_traditional_resolv() {
    echo -e "${GREEN}配置传统 resolv.conf...${NC}"
    
    # 移除不可变属性
    chattr -i /etc/resolv.conf 2>/dev/null || true
    
    # 创建 DNS 配置
    create_resolv_conf /etc/resolv.conf
    
    # 确保文件权限正确
    chmod 644 /etc/resolv.conf
    
    return 0
}

# 7. 创建监控和恢复脚本
create_recovery_script() {
    echo -e "${GREEN}创建 DNS 恢复守护脚本...${NC}"
    
    cat > /usr/local/sbin/dns-lock-monitor.sh << 'SCRIPTEOF'
#!/usr/bin/env bash
# DNS Lock Monitor - 监控并恢复 DNS 配置

EXPECTED_DNS=(
    "8.8.8.8"
    "1.1.1.1"
    "2001:4860:4860::8888"
    "2001:4860:4860::8844"
)

check_and_restore_dns() {
    local needs_restore=0
    
    # 检查 /etc/resolv.conf
    if [ -f /etc/resolv.conf ]; then
        current_count=$(grep -c "nameserver" /etc/resolv.conf 2>/dev/null || echo 0)
        
        # 简单检查：应该有且仅有预期的 DNS 服务器
        for dns in "${EXPECTED_DNS[@]}"; do
            if ! grep -q "$dns" /etc/resolv.conf 2>/dev/null; then
                needs_restore=1
                break
            fi
        done
        
        if [ $needs_restore -eq 1 ]; then
            logger "DNS Lock: DNS 配置已被修改，正在恢复..."
            chattr -i /etc/resolv.conf 2>/dev/null || true
            cat > /etc/resolv.conf << EOF
# DNS Configuration - Locked by dns-lock script
nameserver ${EXPECTED_DNS[0]}
nameserver ${EXPECTED_DNS[1]}
nameserver ${EXPECTED_DNS[2]}
nameserver ${EXPECTED_DNS[3]}
EOF
            chattr +i /etc/resolv.conf 2>/dev/null || true
            logger "DNS Lock: DNS 配置已恢复"
        fi
    fi
}

# 立即检查一次
check_and_restore_dns
SCRIPTEOF
    
    chmod +x /usr/local/sbin/dns-lock-monitor.sh
}

# 8. 设置定时监控任务
setup_cron_monitor() {
    cat > /etc/cron.d/dns-lock << EOF
# DNS Lock Monitor - 每5分钟检查一次 DNS 配置
*/5 * * * * root /usr/local/sbin/dns-lock-monitor.sh
EOF
    
    # 确保 cron 服务运行
    systemctl restart cron 2>/dev/null || systemctl restart crond 2>/dev/null || rc-service cron restart 2>/dev/null || true
}

# 9. 处理 systemd-networkd
setup_systemd_networkd() {
    if systemctl is-active --quiet systemd-networkd 2>/dev/null; then
        echo -e "${GREEN}配置 systemd-networkd...${NC}"
        
        mkdir -p /etc/systemd/network/
        
        # 创建网络配置覆盖
        cat > /etc/systemd/network/90-dns-lock.network << EOF
[Network]
DHCP=yes
DNS=${IPV4_DNS[0]}
DNS=${IPV4_DNS[1]}
DNS=${IPV6_DNS[0]}
DNS=${IPV6_DNS[1]}
EOF
        
        systemctl restart systemd-networkd
        return 0
    fi
    return 1
}

# 主要执行流程
main() {
    local modified=0
    
    # 停止可能修改 DNS 的服务
    systemctl stop resolvconf 2>/dev/null || true
    systemctl stop openresolv 2>/dev/null || true
    
    # 根据检测到的网络管理器进行配置
    for manager in "${MANAGERS[@]}"; do
        case "$manager" in
            "systemd-resolved")
                setup_systemd_resolved && modified=1
                ;;
            "NetworkManager")
                setup_networkmanager && modified=1
                ;;
            "dhcpcd")
                setup_dhcpcd && modified=1
                ;;
            "udhcpc")
                setup_udhcpc && modified=1
                ;;
            "systemd-networkd")
                setup_systemd_networkd && modified=1
                ;;
        esac
    done
    
    # 如果没有任何网络管理器或传统系统，直接配置 resolv.conf
    if [ $modified -eq 0 ] || [ ! -L /etc/resolv.conf ]; then
        setup_traditional_resolv
    fi
    
    # 创建恢复和监控机制
    create_recovery_script
    setup_cron_monitor
    
    # 确保最终 DNS 配置正确
    echo -e "${YELLOW}强制应用 DNS 配置...${NC}"
    chattr -i /etc/resolv.conf 2>/dev/null || true
    create_resolv_conf /etc/resolv.conf
    
    echo -e "${GREEN}=========================================="
    echo "      DNS 锁定配置完成！"
    echo "==========================================${NC}"
    echo ""
    echo "当前 DNS 配置:"
    cat /etc/resolv.conf 2>/dev/null || echo "无法读取 /etc/resolv.conf"
    echo ""
    echo "已启用的保护机制:"
    echo "  ✓ 网络管理器配置锁定"
    echo "  ✓ DHCP 客户端配置锁定"
    echo "  ✓ 文件系统锁定 (chattr +i)"
    echo "  ✓ 定时监控恢复 (每5分钟)"
    echo "  ✓ 系统启动自动恢复"
    echo ""
    echo -e "${YELLOW}提示:${NC}"
    echo "  1. 使用 'cat /etc/resolv.conf' 查看当前配置"
    echo "  2. 使用 'nslookup google.com' 测试 DNS 解析"
    echo "  3. 配置文件已被锁定，需要修改时请先执行:"
    echo "     chattr -i /etc/resolv.conf"
    echo "  4. 日志监控: tail -f /var/log/syslog | grep 'DNS Lock'"
    echo ""
    echo -e "${GREEN}系统将在重启后继续保持此配置。${NC}"
}

# 执行主函数
main

# 尝试测试 DNS 解析
echo ""
echo -e "${YELLOW}正在测试 DNS 解析...${NC}"
nslookup google.com >/dev/null 2>&1 && echo -e "${GREEN}✓ DNS 解析正常${NC}" || echo -e "${RED}✗ DNS 解析可能有问题，请检查配置${NC}"
